Unidades_Edificio/config/routes.rb
Rails.application.routes.draw do
  resources :personas
  resources :apartamentos
  resources :torres

end

Unidades_Edificio/app/models/apartamento.rb
class Apartamento < ActiveRecord::Base
	belongs_to :torre
	belongs_to :persona
end

Unidades_Edificio/app/models/persona.rb
class Persona < ActiveRecord::Base
	has_one :torre
	has_many :apartamento
end

Unidades_Edificio/app/models/torre.rb
class Torre < ActiveRecord::Base
	has_many :apartamento
	has_many :persona, through: :apartamento
end

Unidades_Edificio/app/controllers/apartamentos_controller.rb
class ApartamentosController < ApplicationController
  before_action :set_apartamento, only: [:show, :edit, :update, :destroy]

  # GET /apartamentos
  # GET /apartamentos.json
  def index
    @apartamentos = Apartamento.all
  end

  # GET /apartamentos/1
  # GET /apartamentos/1.json
  def show
    @apartamento = Apartamento.find(params[:id])
  end

  # GET /apartamentos/new
  def new
    @apartamento = Apartamento.new
  end

  # GET /apartamentos/1/edit
  def edit
    @apartamento = Apartamento.find(params[:id])
  end

  # POST /apartamentos
  # POST /apartamentos.json
  def create
    @apartamento = Apartamento.new(apartamento_params)

    respond_to do |format|
      if @apartamento.save
        format.html { redirect_to @apartamento, notice: 'Apartamento was successfully created.' }
        format.json { render :show, status: :created, location: @apartamento }
      else
        format.html { render :new }
        format.json { render json: @apartamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /apartamentos/1
  # PATCH/PUT /apartamentos/1.json
  def update
    respond_to do |format|
      if @apartamento.update(apartamento_params)
        format.html { redirect_to @apartamento, notice: 'Apartamento was successfully updated.' }
        format.json { render :show, status: :ok, location: @apartamento }
      else
        format.html { render :edit }
        format.json { render json: @apartamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apartamentos/1
  # DELETE /apartamentos/1.json
  def destroy
    @apartamento.destroy
    respond_to do |format|
      format.html { redirect_to apartamentos_url, notice: 'Apartamento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_apartamento
      @apartamento = Apartamento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def apartamento_params
      params.require(:apartamento).permit(:numero_puerta, :piso, :torre_id, :persona_id)
    end
end

Unidades_Edificio/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Unidades_Edificio/app/controllers/personas_controller.rb
class PersonasController < ApplicationController
  before_action :set_persona, only: [:show, :edit, :update, :destroy]

  # GET /personas
  # GET /personas.json
  def index
    @personas = Persona.all
  end

  # GET /personas/1
  # GET /personas/1.json
  def show
    @persona = Persona.find(params[:id])
  end

  # GET /personas/new
  def new
    @persona = Persona.new
  end

  # GET /personas/1/edit
  def edit
    @persona = Persona.find(params[:id])
  end

  # POST /personas
  # POST /personas.json
  def create
    @persona = Persona.new(persona_params)

    respond_to do |format|
      if @persona.save
        format.html { redirect_to @persona, notice: 'Persona was successfully created.' }
        format.json { render :show, status: :created, location: @persona }
      else
        format.html { render :new }
        format.json { render json: @persona.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /personas/1
  # PATCH/PUT /personas/1.json
  def update
    respond_to do |format|
      if @persona.update(persona_params)
        format.html { redirect_to @persona, notice: 'Persona was successfully updated.' }
        format.json { render :show, status: :ok, location: @persona }
      else
        format.html { render :edit }
        format.json { render json: @persona.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /personas/1
  # DELETE /personas/1.json
  def destroy
    @persona.destroy
    respond_to do |format|
      format.html { redirect_to personas_url, notice: 'Persona was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_persona
      @persona = Persona.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def persona_params
      params.require(:persona).permit(:identificacion, :name)
    end
end

Unidades_Edificio/app/controllers/torres_controller.rb
class TorresController < ApplicationController
  before_action :set_torre, only: [:show, :edit, :update, :destroy]

  # GET /torres
  # GET /torres.json
  def index
    @torres = Torre.all
  end

  # GET /torres/1
  # GET /torres/1.json
  def show
    @torre = Torre.find(params[:id])
  end

  # GET /torres/new
  def new
    @torre = Torre.new
  end

  # GET /torres/1/edit
  def edit
    @torre = Torre.find(params[:id])
  end

  # POST /torres
  # POST /torres.json
  def create
    @torre = Torre.new(torre_params)

    respond_to do |format|
      if @torre.save
        format.html { redirect_to @torre, notice: 'Torre was successfully created.' }
        format.json { render :show, status: :created, location: @torre }
      else
        format.html { render :new }
        format.json { render json: @torre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /torres/1
  # PATCH/PUT /torres/1.json
  def update
    respond_to do |format|
      if @torre.update(torre_params)
        format.html { redirect_to @torre, notice: 'Torre was successfully updated.' }
        format.json { render :show, status: :ok, location: @torre }
      else
        format.html { render :edit }
        format.json { render json: @torre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /torres/1
  # DELETE /torres/1.json
  def destroy
    @torre.destroy
    respond_to do |format|
      format.html { redirect_to torres_url, notice: 'Torre was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_torre
      @torre = Torre.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def torre_params
      params.require(:torre).permit(:name, :portero)
    end
end

Unidades_Edificio/app/helpers/apartamentos_helper.rb
module ApartamentosHelper
end

Unidades_Edificio/app/helpers/personas_helper.rb
module PersonasHelper
end

Unidades_Edificio/app/helpers/torres_helper.rb
module TorresHelper
end

Unidades_Edificio/app/views/apartamentos/_form.html.erb
<%= form_for(@apartamento) do |f| %>
  <% if @apartamento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@apartamento.errors.count, "error") %> prohibited this apartamento from being saved:</h2>

      <ul>
      <% @apartamento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :numero_puerta %><br>
    <%= f.text_field :numero_puerta %>
  </div>
  <div class="field">
    <%= f.label :piso %><br>
    <%= f.number_field :piso %>
  </div>
  <div class="field">
    <%= f.label :torre_id %><br>
    <%= f.number_field :torre_id %>
  </div>
  <div class="field">
    <%= f.label :persona_id %><br>
    <%= f.number_field :persona_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Unidades_Edificio/app/views/apartamentos/edit.html.erb
<h1>Editing Apartamento</h1>

<%= render 'form' %>

<%= link_to 'Show', @apartamento %> |
<%= link_to 'Back', apartamentos_path %>

Unidades_Edificio/app/views/apartamentos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Apartamentos</h1>

<table>
  <thead>
    <tr>
      <th>Numero puerta</th>
      <th>Piso</th>
      <th>Torre</th>
      <th>Persona</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @apartamentos.each do |apartamento| %>
      <tr>
        <td><%= apartamento.numero_puerta %></td>
        <td><%= apartamento.piso %></td>
        <td><%= apartamento.torre_id %></td>
        <td><%= apartamento.persona_id %></td>
        <td><%= link_to 'Show', apartamento %></td>
        <td><%= link_to 'Edit', edit_apartamento_path(apartamento) %></td>
        <td><%= link_to 'Destroy', apartamento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Apartamento', new_apartamento_path %>

Unidades_Edificio/app/views/apartamentos/new.html.erb
<h1>New Apartamento</h1>

<%= render 'form' %>

<%= link_to 'Back', apartamentos_path %>

Unidades_Edificio/app/views/apartamentos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Numero puerta:</strong>
  <%= @apartamento.numero_puerta %>
</p>

<p>
  <strong>Piso:</strong>
  <%= @apartamento.piso %>
</p>

<p>
  <strong>Torre:</strong>
  <%= @apartamento.torre_id %>
</p>

<p>
  <strong>Persona:</strong>
  <%= @apartamento.persona_id %>
</p>

<%= link_to 'Edit', edit_apartamento_path(@apartamento) %> |
<%= link_to 'Back', apartamentos_path %>

Unidades_Edificio/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UnidadesEdificio</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header class="navbar navbar-fixed-top navbar-inverse">
           <div class="container">
             <%= link_to "sample app", '#', id: "logo" %>
             <nav>
               <ul class="nav navbar-nav navbar-right">
                 <li><%= link_to "Home",   '#' %></li>
                 <li><%= link_to "Help",  '#' %></li>
                 <li><%= link_to "Log in", '#' %></li>
               </ul>
             </nav>
           </div>
     </header>
     <br>
     <br>
     <br>
     <br>

<%= yield %>

</body>
</html>

Unidades_Edificio/app/views/personas/_form.html.erb
<%= form_for(@persona) do |f| %>
  <% if @persona.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@persona.errors.count, "error") %> prohibited this persona from being saved:</h2>

      <ul>
      <% @persona.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :identificacion %><br>
    <%= f.number_field :identificacion %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Unidades_Edificio/app/views/personas/edit.html.erb
<h1>Editing Persona</h1>

<%= render 'form' %>

<%= link_to 'Show', @persona %> |
<%= link_to 'Back', personas_path %>

Unidades_Edificio/app/views/personas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Personas</h1>

<table>
  <thead>
    <tr>
      <th>Identificacion</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @personas.each do |persona| %>
      <tr>
        <td><%= persona.identificacion %></td>
        <td><%= persona.name %></td>
        <td><%= link_to 'Show', persona %></td>
        <td><%= link_to 'Edit', edit_persona_path(persona) %></td>
        <td><%= link_to 'Destroy', persona, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Persona', new_persona_path %>

Unidades_Edificio/app/views/personas/new.html.erb
<h1>New Persona</h1>

<%= render 'form' %>

<%= link_to 'Back', personas_path %>

Unidades_Edificio/app/views/personas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Identificacion:</strong>
  <%= @persona.identificacion %>
</p>

<p>
  <strong>Name:</strong>
  <%= @persona.name %>
</p>

<%= link_to 'Edit', edit_persona_path(@persona) %> |
<%= link_to 'Back', personas_path %>

Unidades_Edificio/app/views/torres/_form.html.erb
<%= form_for(@torre) do |f| %>
  <% if @torre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@torre.errors.count, "error") %> prohibited this torre from being saved:</h2>

      <ul>
      <% @torre.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :portero %><br>
    <%= f.text_field :portero %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Unidades_Edificio/app/views/torres/edit.html.erb
<h1>Editing Torre</h1>

<%= render 'form' %>

<%= link_to 'Show', @torre %> |
<%= link_to 'Back', torres_path %>

Unidades_Edificio/app/views/torres/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Torres</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Portero</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @torres.each do |torre| %>
      <tr>
        <td><%= torre.name %></td>
        <td><%= torre.portero %></td>
        <td><%= link_to 'Show', torre %></td>
        <td><%= link_to 'Edit', edit_torre_path(torre) %></td>
        <td><%= link_to 'Destroy', torre, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Torre', new_torre_path %>

Unidades_Edificio/app/views/torres/new.html.erb
<h1>New Torre</h1>

<%= render 'form' %>

<%= link_to 'Back', torres_path %>

Unidades_Edificio/app/views/torres/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @torre.name %>
</p>

<p>
  <strong>Portero:</strong>
  <%= @torre.portero %>
</p>

<%= link_to 'Edit', edit_torre_path(@torre) %> |
<%= link_to 'Back', torres_path %>